import 'package:flutter/material.dart';

enum ReadingLevelId {
  level1, // Level 1: Pengenalan Fonem & Bunyi Huruf (A, I, U, E, O, B, M, S, P)
  level2, // Level 2: Suku Kata Terbuka (BA, BI, BU, BE, BO, MA, SA)
  level3, // Level 3: Kata 2 Suku Kata (BOLA, BUKU, MAMA, MATA, SUSU)
  level4, // Level 4: Konsonan Mati / Tertutup (MAKAN, MINUM, IKAN, KUCING)
  level5, // Level 5: Kalimat Pendek & Mini Cerita Interaktif
}

class ReadingQuizQuestion {
  final String questionText;
  final String speechAudio;
  final String? targetWordOrLetter;
  final String? illustrationEmoji;
  final List<String> options;
  final int correctOptionIndex;
  final String hintExplanation;

  const ReadingQuizQuestion({
    required this.questionText,
    required this.speechAudio,
    this.targetWordOrLetter,
    this.illustrationEmoji,
    required this.options,
    required this.correctOptionIndex,
    required this.hintExplanation,
  });
}

class ReadingLessonItem {
  final String id;
  final String title;
  final String phoneticSound; // e.g. "/b/ seperti bola"
  final String previewText;   // e.g. "B" or "BA" or "BOLA"
  final String illustrationEmoji;
  final String speechText;
  final List<String> syllables; // For interactive assembly (e.g. ['BO', 'LA'])
  final Color themeColor;

  const ReadingLessonItem({
    required this.id,
    required this.title,
    required this.phoneticSound,
    required this.previewText,
    required this.illustrationEmoji,
    required this.speechText,
    this.syllables = const [],
    this.themeColor = const Color(0xFF0284C7),
  });
}

class ReadingLevel {
  final ReadingLevelId id;
  final int levelNumber;
  final String title;
  final String subtitle;
  final String tag;
  final Color primaryColor;
  final Color lightBgColor;
  final String iconEmoji;
  final List<ReadingLessonItem> lessons;
  final List<ReadingQuizQuestion> testQuestions;

  const ReadingLevel({
    required this.id,
    required this.levelNumber,
    required this.title,
    required this.subtitle,
    required this.tag,
    required this.primaryColor,
    required this.lightBgColor,
    required this.iconEmoji,
    required this.lessons,
    required this.testQuestions,
  });
}

class ReadingRepository {
  static const List<ReadingLevel> levels = [
    // =========================================================================
    // LEVEL 1: Bunyi Fonem Vokal Lengkap & Konsonan Fondasi Dasar (A - Z Dasar)
    // =========================================================================
    ReadingLevel(
      id: ReadingLevelId.level1,
      levelNumber: 1,
      title: 'Bunyi Huruf Pertama',
      subtitle: 'Mengenal bunyi fonem vokal & konsonan dasar anak',
      tag: 'DASAR 0',
      primaryColor: Color(0xFFEF4444),
      lightBgColor: Color(0xFFFEF2F2),
      iconEmoji: '🔤',
      lessons: [
        ReadingLessonItem(
          id: 'v_a',
          title: 'Huruf A',
          phoneticSound: 'Mulut terbuka lebar: /a-a-a/',
          previewText: 'A',
          illustrationEmoji: '🍎',
          speechText: 'A... Apel merah manis sekali!',
          themeColor: Color(0xFFEF4444),
        ),
        ReadingLessonItem(
          id: 'v_i',
          title: 'Huruf I',
          phoneticSound: 'Bibir tersenyum lebar: /i-i-i/',
          previewText: 'I',
          illustrationEmoji: '🐟',
          speechText: 'I... Ikan berenang lincah di air!',
          themeColor: Color(0xFF0284C7),
        ),
        ReadingLessonItem(
          id: 'v_u',
          title: 'Huruf U',
          phoneticSound: 'Bibir dimajukan bulat: /u-u-u/',
          previewText: 'U',
          illustrationEmoji: '🐛',
          speechText: 'U... Ulat hijau merayap di daun!',
          themeColor: Color(0xFF16A34A),
        ),
        ReadingLessonItem(
          id: 'v_e',
          title: 'Huruf E',
          phoneticSound: 'Bibir santai terbuka: /e-e-e/',
          previewText: 'E',
          illustrationEmoji: '🍦',
          speechText: 'E... Es krim manis dan dingin!',
          themeColor: Color(0xFFEC4899),
        ),
        ReadingLessonItem(
          id: 'v_o',
          title: 'Huruf O',
          phoneticSound: 'Mulut bulat bundar: /o-o-o/',
          previewText: 'O',
          illustrationEmoji: '🍩',
          speechText: 'O... Donat bulat bertabur cokelat!',
          themeColor: Color(0xFFF59E0B),
        ),
        ReadingLessonItem(
          id: 'c_b',
          title: 'Huruf B',
          phoneticSound: 'Dua bibir meletup: /b-b-b/',
          previewText: 'B',
          illustrationEmoji: '⚽',
          speechText: 'B... Bola memantul boing boing!',
          themeColor: Color(0xFF3B82F6),
        ),
        ReadingLessonItem(
          id: 'c_m',
          title: 'Huruf M',
          phoneticSound: 'Bibir terkatup rapat: /m-m-m/',
          previewText: 'M',
          illustrationEmoji: '🐱',
          speechText: 'M... Meong kucing manis memanggil!',
          themeColor: Color(0xFF8B5CF6),
        ),
        ReadingLessonItem(
          id: 'c_s',
          title: 'Huruf S',
          phoneticSound: 'Udara mendesis di gigi: /s-s-s/',
          previewText: 'S',
          illustrationEmoji: '🥛',
          speechText: 'S... Susu putih sehat untuk tubuh!',
          themeColor: Color(0xFF06B6D4),
        ),
        ReadingLessonItem(
          id: 'c_p',
          title: 'Huruf P',
          phoneticSound: 'Letupan bibir ringan: /p-p-p/',
          previewText: 'P',
          illustrationEmoji: '🍌',
          speechText: 'P... Pisang kuning manis kesukaan!',
          themeColor: Color(0xFFEAB308),
        ),
        ReadingLessonItem(
          id: 'c_t',
          title: 'Huruf T',
          phoneticSound: 'Lidah mengetuk gigi atas: /t-t-t/',
          previewText: 'T',
          illustrationEmoji: '🧢',
          speechText: 'T... Topi keren dipakai di kepala!',
          themeColor: Color(0xFF14B8A6),
        ),
        ReadingLessonItem(
          id: 'c_k',
          title: 'Huruf K',
          phoneticSound: 'Bunyi di pangkal tenggorokan: /k-k-k/',
          previewText: 'K',
          illustrationEmoji: '🐴',
          speechText: 'K... Kuda gagah berlari kencang!',
          themeColor: Color(0xFFD97706),
        ),
        ReadingLessonItem(
          id: 'c_l',
          title: 'Huruf L',
          phoneticSound: 'Ujung lidah ke langit-langit: /l-l-l/',
          previewText: 'L',
          illustrationEmoji: '🍋',
          speechText: 'L... Lemon kuning segar beraroma wangi!',
          themeColor: Color(0xFF84CC16),
        ),
        ReadingLessonItem(
          id: 'c_d',
          title: 'Huruf D',
          phoneticSound: 'Lidah menekan gusi depan: /d-d-d/',
          previewText: 'D',
          illustrationEmoji: '🍃',
          speechText: 'D... Daun hijau segar di ranting pohon!',
          themeColor: Color(0xFF10B981),
        ),
      ],
      testQuestions: [
        ReadingQuizQuestion(
          questionText: 'Manakah huruf yang berbunyi seperti awal kata "Apel"?',
          speechAudio: 'Manakah huruf yang berbunyi seperti awal kata Apel?',
          illustrationEmoji: '🍎',
          options: ['A', 'I', 'U'],
          correctOptionIndex: 0,
          hintExplanation: 'Apel diawali dengan huruf vokal A!',
        ),
        ReadingQuizQuestion(
          questionText: 'Manakah huruf dengan bunyi /B/ seperti pada kata "Bola"?',
          speechAudio: 'Manakah huruf dengan bunyi B seperti pada kata Bola?',
          illustrationEmoji: '⚽',
          options: ['M', 'B', 'P'],
          correctOptionIndex: 1,
          hintExplanation: 'Bola memantul diawali dengan huruf B!',
        ),
        ReadingQuizQuestion(
          questionText: 'Huruf apakah yang bentuknya bulat sempurna seperti donat?',
          speechAudio: 'Huruf apakah yang bentuknya bulat seperti donat?',
          illustrationEmoji: '🍩',
          options: ['E', 'U', 'O'],
          correctOptionIndex: 2,
          hintExplanation: 'Huruf O berbentuk bulat bundar!',
        ),
        ReadingQuizQuestion(
          questionText: 'Manakah huruf yang berbunyi mendesis /S/ seperti "Susu"?',
          speechAudio: 'Manakah huruf yang berbunyi mendesis S seperti Susu?',
          illustrationEmoji: '🥛',
          options: ['T', 'S', 'L'],
          correctOptionIndex: 1,
          hintExplanation: 'Susu diawali dengan desisan huruf S!',
        ),
        ReadingQuizQuestion(
          questionText: 'Manakah huruf awal dari kata "Ikan"?',
          speechAudio: 'Manakah huruf awal dari kata Ikan?',
          illustrationEmoji: '🐟',
          options: ['I', 'A', 'E'],
          correctOptionIndex: 0,
          hintExplanation: 'I-K-A-N diawali dengan huruf I!',
        ),
        ReadingQuizQuestion(
          questionText: 'Manakah huruf yang berbunyi ketukan /K/ seperti pada "Kuda"?',
          speechAudio: 'Manakah huruf yang berbunyi ketukan K seperti pada Kuda?',
          illustrationEmoji: '🐴',
          options: ['B', 'D', 'K'],
          correctOptionIndex: 2,
          hintExplanation: 'Kuda berlari diawali huruf K!',
        ),
      ],
    ),

    // =========================================================================
    // LEVEL 2: Suku Kata Terbuka Komprehensif (Konsonan + Vokal: BA, MA, PA, KA, SA, TA, LA, DA)
    // =========================================================================
    ReadingLevel(
      id: ReadingLevelId.level2,
      levelNumber: 2,
      title: 'Suku Kata Ajaib',
      subtitle: 'Menggabungkan 2 huruf jadi 1 bunyi suku kata terbuka',
      tag: 'SUKU KATA',
      primaryColor: Color(0xFFF97316),
      lightBgColor: Color(0xFFFFF7ED),
      iconEmoji: '🧩',
      lessons: [
        ReadingLessonItem(
          id: 'syll_ba',
          title: 'BA',
          phoneticSound: 'B bertemu A ➔ BA',
          previewText: 'BA',
          illustrationEmoji: '🎈',
          speechText: 'B... A... BA! Balon warna-warni terbang!',
          themeColor: Color(0xFFF97316),
        ),
        ReadingLessonItem(
          id: 'syll_bi',
          title: 'BI',
          phoneticSound: 'B bertemu I ➔ BI',
          previewText: 'BI',
          illustrationEmoji: '⭐',
          speechText: 'B... I... BI! Bintang terang di langit!',
          themeColor: Color(0xFFF59E0B),
        ),
        ReadingLessonItem(
          id: 'syll_bu',
          title: 'BU',
          phoneticSound: 'B bertemu U ➔ BU',
          previewText: 'BU',
          illustrationEmoji: '📚',
          speechText: 'B... U... BU! Buku ilmu pengetahuan!',
          themeColor: Color(0xFF10B981),
        ),
        ReadingLessonItem(
          id: 'syll_ma',
          title: 'MA',
          phoneticSound: 'M bertemu A ➔ MA',
          previewText: 'MA',
          illustrationEmoji: '👩',
          speechText: 'M... A... MA! Mama tersayang peluk aku!',
          themeColor: Color(0xFFEC4899),
        ),
        ReadingLessonItem(
          id: 'syll_mi',
          title: 'MI',
          phoneticSound: 'M bertemu I ➔ MI',
          previewText: 'MI',
          illustrationEmoji: '🍜',
          speechText: 'M... I... MI! Mi kuah hangat sedap!',
          themeColor: Color(0xFFE11D48),
        ),
        ReadingLessonItem(
          id: 'syll_pa',
          title: 'PA',
          phoneticSound: 'P bertemu A ➔ PA',
          previewText: 'PA',
          illustrationEmoji: '👨',
          speechText: 'P... A... PA! Papa hebat teman bermain!',
          themeColor: Color(0xFF8B5CF6),
        ),
        ReadingLessonItem(
          id: 'syll_pi',
          title: 'PI',
          phoneticSound: 'P bertemu I ➔ PI',
          previewText: 'PI',
          illustrationEmoji: '😊',
          speechText: 'P... I... PI! Pipi merah merona gembira!',
          themeColor: Color(0xFF3B82F6),
        ),
        ReadingLessonItem(
          id: 'syll_sa',
          title: 'SA',
          phoneticSound: 'S bertemu A ➔ SA',
          previewText: 'SA',
          illustrationEmoji: '🧹',
          speechText: 'S... A... SA! Sapu lantai sampai bersih!',
          themeColor: Color(0xFF14B8A6),
        ),
        ReadingLessonItem(
          id: 'syll_su',
          title: 'SU',
          phoneticSound: 'S bertemu U ➔ SU',
          previewText: 'SU',
          illustrationEmoji: '🥛',
          speechText: 'S... U... SU! Susu segar sehat setiap hari!',
          themeColor: Color(0xFF0284C7),
        ),
        ReadingLessonItem(
          id: 'syll_ka',
          title: 'KA',
          phoneticSound: 'K bertemu A ➔ KA',
          previewText: 'KA',
          illustrationEmoji: '🦶',
          speechText: 'K... A... KA! Kaki kuat untuk melangkah!',
          themeColor: Color(0xFFD97706),
        ),
        ReadingLessonItem(
          id: 'syll_ku',
          title: 'KU',
          phoneticSound: 'K bertemu U ➔ KU',
          previewText: 'KU',
          illustrationEmoji: '🐴',
          speechText: 'K... U... KU! Kuda kencang berlari cepat!',
          themeColor: Color(0xFFCA8A04),
        ),
        ReadingLessonItem(
          id: 'syll_ta',
          title: 'TA',
          phoneticSound: 'T bertemu A ➔ TA',
          previewText: 'TA',
          illustrationEmoji: '🪴',
          speechText: 'T... A... TA! Tanaman disiram tumbuh subur!',
          themeColor: Color(0xFF16A34A),
        ),
        ReadingLessonItem(
          id: 'syll_da',
          title: 'DA',
          phoneticSound: 'D bertemu A ➔ DA',
          previewText: 'DA',
          illustrationEmoji: '🍃',
          speechText: 'D... A... DA! Daun rindang menyejukkan!',
          themeColor: Color(0xFF059669),
        ),
        ReadingLessonItem(
          id: 'syll_la',
          title: 'LA',
          phoneticSound: 'L bertemu A ➔ LA',
          previewText: 'LA',
          illustrationEmoji: '🕯️',
          speechText: 'L... A... LA! Lampu terang benderang!',
          themeColor: Color(0xFF6366F1),
        ),
      ],
      testQuestions: [
        ReadingQuizQuestion(
          questionText: 'Jika huruf B digabung dengan A, bunyinya menjadi apa?',
          speechAudio: 'Jika huruf B digabung dengan A, bunyinya menjadi apa?',
          targetWordOrLetter: 'B + A = ?',
          options: ['BO', 'BU', 'BA'],
          correctOptionIndex: 2,
          hintExplanation: 'B bertemu A bunyinya BA!',
        ),
        ReadingQuizQuestion(
          questionText: 'Manakah suku kata awal dari kata "Buku"?',
          speechAudio: 'Manakah suku kata awal dari kata Buku?',
          illustrationEmoji: '📚',
          options: ['BU', 'BI', 'BA'],
          correctOptionIndex: 0,
          hintExplanation: 'Buku diawali dengan BU!',
        ),
        ReadingQuizQuestion(
          questionText: 'Jika M digabung dengan A, bunyinya menjadi apa?',
          speechAudio: 'Jika M digabung dengan A, bunyinya menjadi apa?',
          targetWordOrLetter: 'M + A = ?',
          options: ['MU', 'MI', 'MA'],
          correctOptionIndex: 2,
          hintExplanation: 'M bertemu A bunyinya MA!',
        ),
        ReadingQuizQuestion(
          questionText: 'Manakah suku kata awal dari kata "Susu"?',
          speechAudio: 'Manakah suku kata awal dari kata Susu?',
          illustrationEmoji: '🥛',
          options: ['SA', 'SU', 'SI'],
          correctOptionIndex: 1,
          hintExplanation: 'Susu diawali dengan SU!',
        ),
        ReadingQuizQuestion(
          questionText: 'Manakah suku kata awal dari kata "Kaki"?',
          speechAudio: 'Manakah suku kata awal dari kata Kaki?',
          illustrationEmoji: '🦶',
          options: ['KU', 'KI', 'KA'],
          correctOptionIndex: 2,
          hintExplanation: 'Kaki diawali dengan suku kata KA!',
        ),
        ReadingQuizQuestion(
          questionText: 'P + I digabung berbunyi apa?',
          speechAudio: 'P dan I digabung berbunyi apa?',
          targetWordOrLetter: 'P + I = ?',
          options: ['PA', 'PI', 'PU'],
          correctOptionIndex: 1,
          hintExplanation: 'P bertemu I berbunyi PI!',
        ),
      ],
    ),

    // =========================================================================
    // LEVEL 3: Kata 2 Suku Kata Utuh (KV-KV: BOLA, BUKU, MAMA, PAPA, SUSU, KUDA, MEJA, TOPI, SAPU, ROTI, GIGI, NAMA)
    // =========================================================================
    ReadingLevel(
      id: ReadingLevelId.level3,
      levelNumber: 3,
      title: 'Kata Pertama Ali',
      subtitle: 'Membaca kata utuh dari 2 suku kata bermakna (KV-KV)',
      tag: 'KATA UTUH',
      primaryColor: Color(0xFF10B981),
      lightBgColor: Color(0xFFF0FDF4),
      iconEmoji: '📖',
      lessons: [
        ReadingLessonItem(
          id: 'w_bola',
          title: 'BOLA',
          phoneticSound: 'BO - LA',
          previewText: 'BOLA',
          illustrationEmoji: '⚽',
          speechText: 'BO... LA... BOLA! Ayo tendang bola ke depan!',
          syllables: ['BO', 'LA'],
          themeColor: Color(0xFF3B82F6),
        ),
        ReadingLessonItem(
          id: 'w_buku',
          title: 'BUKU',
          phoneticSound: 'BU - KU',
          previewText: 'BUKU',
          illustrationEmoji: '📕',
          speechText: 'BU... KU... BUKU! Mari membaca buku jendela dunia!',
          syllables: ['BU', 'KU'],
          themeColor: Color(0xFFEF4444),
        ),
        ReadingLessonItem(
          id: 'w_mama',
          title: 'MAMA',
          phoneticSound: 'MA - MA',
          previewText: 'MAMA',
          illustrationEmoji: '👩',
          speechText: 'MA... MA... MAMA! Mama peluk erat penuh kasih!',
          syllables: ['MA', 'MA'],
          themeColor: Color(0xFFEC4899),
        ),
        ReadingLessonItem(
          id: 'w_papa',
          title: 'PAPA',
          phoneticSound: 'PA - PA',
          previewText: 'PAPA',
          illustrationEmoji: '👨',
          speechText: 'PA... PA... PAPA! Papa mengajak Ali bermain!',
          syllables: ['PA', 'PA'],
          themeColor: Color(0xFF8B5CF6),
        ),
        ReadingLessonItem(
          id: 'w_mata',
          title: 'MATA',
          phoneticSound: 'MA - TA',
          previewText: 'MATA',
          illustrationEmoji: '👀',
          speechText: 'MA... TA... MATA! Mata sehat melihat dunia!',
          syllables: ['MA', 'TA'],
          themeColor: Color(0xFF6366F1),
        ),
        ReadingLessonItem(
          id: 'w_susu',
          title: 'SUSU',
          phoneticSound: 'SU - SU',
          previewText: 'SUSU',
          illustrationEmoji: '🥛',
          speechText: 'SU... SU... SUSU! Minum susu hangat sebelum tidur!',
          syllables: ['SU', 'SU'],
          themeColor: Color(0xFF0284C7),
        ),
        ReadingLessonItem(
          id: 'w_kuda',
          title: 'KUDA',
          phoneticSound: 'KU - DA',
          previewText: 'KUDA',
          illustrationEmoji: '🐴',
          speechText: 'KU... DA... KUDA! Kuda berlari gagah di padang rumput!',
          syllables: ['KU', 'DA'],
          themeColor: Color(0xFFD97706),
        ),
        ReadingLessonItem(
          id: 'w_meja',
          title: 'MEJA',
          phoneticSound: 'ME - JA',
          previewText: 'MEJA',
          illustrationEmoji: '🪵',
          speechText: 'ME... JA... MEJA! Buku ditaruh di atas meja belajar!',
          syllables: ['ME', 'JA'],
          themeColor: Color(0xFFB45309),
        ),
        ReadingLessonItem(
          id: 'w_topi',
          title: 'TOPI',
          phoneticSound: 'TO - PI',
          previewText: 'TOPI',
          illustrationEmoji: '🧢',
          speechText: 'TO... PI... TOPI! Pakai topi saat matahari terik!',
          syllables: ['TO', 'PI'],
          themeColor: Color(0xFF14B8A6),
        ),
        ReadingLessonItem(
          id: 'w_sapu',
          title: 'SAPU',
          phoneticSound: 'SA - PU',
          previewText: 'SAPU',
          illustrationEmoji: '🧹',
          speechText: 'SA... PU... SAPU! Bersihkan lantai dengan sapu!',
          syllables: ['SA', 'PU'],
          themeColor: Color(0xFF16A34A),
        ),
        ReadingLessonItem(
          id: 'w_roti',
          title: 'ROTI',
          phoneticSound: 'RO - TI',
          previewText: 'ROTI',
          illustrationEmoji: '🍞',
          speechText: 'RO... TI... ROTI! Roti selai sarapan lezat!',
          syllables: ['RO', 'TI'],
          themeColor: Color(0xFFEAB308),
        ),
        ReadingLessonItem(
          id: 'w_gigi',
          title: 'GIGI',
          phoneticSound: 'GI - GI',
          previewText: 'GIGI',
          illustrationEmoji: '🦷',
          speechText: 'GI... GI... GIGI! Gosok gigi putih bersih bercahaya!',
          syllables: ['GI', 'GI'],
          themeColor: Color(0xFF06B6D4),
        ),
      ],
      testQuestions: [
        ReadingQuizQuestion(
          questionText: 'Pilih kata yang tepat untuk gambar ini:',
          speechAudio: 'Pilih kata yang tepat untuk gambar bola!',
          illustrationEmoji: '⚽',
          options: ['BUKU', 'BOLA', 'MATA'],
          correctOptionIndex: 1,
          hintExplanation: 'Ini adalah B-O-L-A (BOLA)!',
        ),
        ReadingQuizQuestion(
          questionText: 'Jika potongan [ MA ] dan [ TA ] digabung, menjadi kata apa?',
          speechAudio: 'Jika potongan MA dan TA digabung, menjadi kata apa?',
          targetWordOrLetter: '[ MA ] + [ TA ]',
          options: ['MATA', 'MAMA', 'MANA'],
          correctOptionIndex: 0,
          hintExplanation: 'MA dan TA menjadi MATA!',
        ),
        ReadingQuizQuestion(
          questionText: 'Manakah tulisan kata "SUSU"?',
          speechAudio: 'Manakah tulisan kata SUSU?',
          illustrationEmoji: '🥛',
          options: ['SASA', 'SOTO', 'SUSU'],
          correctOptionIndex: 2,
          hintExplanation: 'S-U-S-U dibaca SUSU!',
        ),
        ReadingQuizQuestion(
          questionText: 'Pilihlah kata yang tepat untuk gambar kuda gagah ini:',
          speechAudio: 'Pilihlah kata yang tepat untuk gambar kuda!',
          illustrationEmoji: '🐴',
          options: ['KURA', 'KUDA', 'KACA'],
          correctOptionIndex: 1,
          hintExplanation: 'KU + DA menjadi KUDA!',
        ),
        ReadingQuizQuestion(
          questionText: 'Potongan kata [ RO ] + [ TI ] digabung menjadi apa?',
          speechAudio: 'Potongan kata RO dan TI digabung menjadi apa?',
          targetWordOrLetter: '[ RO ] + [ TI ]',
          options: ['RODA', 'ROTI', 'RASA'],
          correctOptionIndex: 1,
          hintExplanation: 'RO dan TI menjadi ROTI!',
        ),
        ReadingQuizQuestion(
          questionText: 'Kata apakah yang tepat untuk penutup kepala ini?',
          speechAudio: 'Kata apakah yang tepat untuk topi?',
          illustrationEmoji: '🧢',
          options: ['TOPI', 'TALI', 'TACI'],
          correctOptionIndex: 0,
          hintExplanation: 'T-O-P-I adalah TOPI!',
        ),
      ],
    ),

    // =========================================================================
    // LEVEL 4: Suku Kata Tertutup & Konsonan Akhir (KVK: MAKAN, MINUM, IKAN, KUCING, AYAM, HUJAN, POHON, RUMAH, JERUK, BULAN)
    // =========================================================================
    ReadingLevel(
      id: ReadingLevelId.level4,
      levelNumber: 4,
      title: 'Tantangan Huruf Mati',
      subtitle: 'Membaca kata dengan akhiran konsonan & diftong (KVK / Tertutup)',
      tag: 'KONSONAN MATI',
      primaryColor: Color(0xFF8B5CF6),
      lightBgColor: Color(0xFFF5F3FF),
      iconEmoji: '🎯',
      lessons: [
        ReadingLessonItem(
          id: 'w_makan',
          title: 'MAKAN',
          phoneticSound: 'MA - KAN',
          previewText: 'MAKAN',
          illustrationEmoji: '🍚',
          speechText: 'MA... KAN... MAKAN! Ali makan nasi hangat sedap!',
          syllables: ['MA', 'KAN'],
          themeColor: Color(0xFF10B981),
        ),
        ReadingLessonItem(
          id: 'w_minum',
          title: 'MINUM',
          phoneticSound: 'MI - NUM',
          previewText: 'MINUM',
          illustrationEmoji: '🥤',
          speechText: 'MI... NUM... MINUM! Minum air putih yang segar!',
          syllables: ['MI', 'NUM'],
          themeColor: Color(0xFF0284C7),
        ),
        ReadingLessonItem(
          id: 'w_ikan',
          title: 'IKAN',
          phoneticSound: 'I - KAN',
          previewText: 'IKAN',
          illustrationEmoji: '🐟',
          speechText: 'I... KAN... IKAN! Ikan berenang cepat di kolam!',
          syllables: ['I', 'KAN'],
          themeColor: Color(0xFF3B82F6),
        ),
        ReadingLessonItem(
          id: 'w_kucing',
          title: 'KUCING',
          phoneticSound: 'KU - CING',
          previewText: 'KUCING',
          illustrationEmoji: '🐱',
          speechText: 'KU... CING... KUCING! Kucing belang manja mengeong!',
          syllables: ['KU', 'CING'],
          themeColor: Color(0xFFF59E0B),
        ),
        ReadingLessonItem(
          id: 'w_ayam',
          title: 'AYAM',
          phoneticSound: 'A - YAM',
          previewText: 'AYAM',
          illustrationEmoji: '🐓',
          speechText: 'A... YAM... AYAM! Ayam jantan berkokok di pagi hari!',
          syllables: ['A', 'YAM'],
          themeColor: Color(0xFFEF4444),
        ),
        ReadingLessonItem(
          id: 'w_hujan',
          title: 'HUJAN',
          phoneticSound: 'HU - JAN',
          previewText: 'HUJAN',
          illustrationEmoji: '🌧️',
          speechText: 'HU... JAN... HUJAN! Air hujan turun menyuburkan bumi!',
          syllables: ['HU', 'JAN'],
          themeColor: Color(0xFF06B6D4),
        ),
        ReadingLessonItem(
          id: 'w_pohon',
          title: 'POHON',
          phoneticSound: 'PO - HON',
          previewText: 'POHON',
          illustrationEmoji: '🌳',
          speechText: 'PO... HON... POHON! Pohon rindang buahnya manis lebat!',
          syllables: ['PO', 'HON'],
          themeColor: Color(0xFF16A34A),
        ),
        ReadingLessonItem(
          id: 'w_rumah',
          title: 'RUMAH',
          phoneticSound: 'RU - MAH',
          previewText: 'RUMAH',
          illustrationEmoji: '🏡',
          speechText: 'RU... MAH... RUMAH! Rumah nyaman tempat berkumpul keluarga!',
          syllables: ['RU', 'MAH'],
          themeColor: Color(0xFFEC4899),
        ),
        ReadingLessonItem(
          id: 'w_jeruk',
          title: 'JERUK',
          phoneticSound: 'JE - RUK',
          previewText: 'JERUK',
          illustrationEmoji: '🍊',
          speechText: 'JE... RUK... JERUK! Buah jeruk segar kaya vitamin C!',
          syllables: ['JE', 'RUK'],
          themeColor: Color(0xFFF97316),
        ),
        ReadingLessonItem(
          id: 'w_bulan',
          title: 'BULAN',
          phoneticSound: 'BU - LAN',
          previewText: 'BULAN',
          illustrationEmoji: '🌙',
          speechText: 'BU... LAN... BULAN! Bulan purnama bersinar di malam hari!',
          syllables: ['BU', 'LAN'],
          themeColor: Color(0xFF6366F1),
        ),
      ],
      testQuestions: [
        ReadingQuizQuestion(
          questionText: 'Manakah kata yang berakhiran huruf N?',
          speechAudio: 'Manakah kata yang berakhiran huruf N?',
          illustrationEmoji: '🍚',
          options: ['MAKAN', 'MINUM', 'RUMAH'],
          correctOptionIndex: 0,
          hintExplanation: 'MA-KAN berakhiran bunyi konsonan N!',
        ),
        ReadingQuizQuestion(
          questionText: 'Pilihlah kata yang tepat untuk hewan lucu bersuara meong ini:',
          speechAudio: 'Pilihlah kata yang tepat untuk kucing!',
          illustrationEmoji: '🐱',
          options: ['KAMBING', 'KUCING', 'KELINCI'],
          correctOptionIndex: 1,
          hintExplanation: 'Ini adalah KU-CING (KUCING)!',
        ),
        ReadingQuizQuestion(
          questionText: 'Kata "MINUM" berakhiran dengan bunyi huruf apa?',
          speechAudio: 'Kata MINUM berakhiran dengan bunyi huruf apa?',
          targetWordOrLetter: 'MI - NUM',
          options: ['M', 'N', 'K'],
          correctOptionIndex: 0,
          hintExplanation: 'MINUM berakhiran huruf M!',
        ),
        ReadingQuizQuestion(
          questionText: 'Manakah kata yang tepat untuk gambar tempat tinggal keluarga ini?',
          speechAudio: 'Manakah kata yang tepat untuk rumah?',
          illustrationEmoji: '🏡',
          options: ['RUMAH', 'RAMBUT', 'RANTING'],
          correctOptionIndex: 0,
          hintExplanation: 'RU + MAH adalah RUMAH!',
        ),
        ReadingQuizQuestion(
          questionText: 'Kata apakah yang berakhiran bunyi [ YAM ]?',
          speechAudio: 'Kata apakah yang berakhiran bunyi YAM?',
          illustrationEmoji: '🐓',
          options: ['APEL', 'AYAM', 'ANGGUR'],
          correctOptionIndex: 1,
          hintExplanation: 'A-Y-A-M berakhiran YAM!',
        ),
        ReadingQuizQuestion(
          questionText: 'Manakah kata dengan akhiran bunyi [ RUK ]?',
          speechAudio: 'Manakah kata dengan akhiran bunyi RUK?',
          illustrationEmoji: '🍊',
          options: ['JERUK', 'JAMUR', 'JARUM'],
          correctOptionIndex: 0,
          hintExplanation: 'JE-RUK adalah buah jeruk!',
        ),
      ],
    ),

    // =========================================================================
    // LEVEL 5: Kalimat Pendek, Cerita Interaktif & Pemahaman Membaca Lancar
    // =========================================================================
    ReadingLevel(
      id: ReadingLevelId.level5,
      levelNumber: 5,
      title: 'Membaca Cerita Hebat',
      subtitle: 'Membaca lancar kalimat pendek dan mini cerita bergambar seru',
      tag: 'MAHIR',
      primaryColor: Color(0xFF0284C7),
      lightBgColor: Color(0xFFF0F9FF),
      iconEmoji: '🌟',
      lessons: [
        ReadingLessonItem(
          id: 's_1',
          title: 'Ali Suka Apel',
          phoneticSound: 'Kalimat 4 Kata',
          previewText: 'Ali suka makan apel merah.',
          illustrationEmoji: '👦🍎',
          speechText: 'Ali suka makan apel merah yang manis dan segar!',
          syllables: ['Ali', 'suka', 'makan', 'apel', 'merah.'],
          themeColor: Color(0xFF0284C7),
        ),
        ReadingLessonItem(
          id: 's_2',
          title: 'Kucing Lucu Tidur',
          phoneticSound: 'Kalimat 5 Kata',
          previewText: 'Kucing manis tidur di sofa empuk.',
          illustrationEmoji: '🐱🛋️',
          speechText: 'Kucing manis tidur nyenyak di atas sofa empuk rumah!',
          syllables: ['Kucing', 'manis', 'tidur', 'di', 'sofa', 'empuk.'],
          themeColor: Color(0xFFF59E0B),
        ),
        ReadingLessonItem(
          id: 's_3',
          title: 'Ayo Main Bola',
          phoneticSound: 'Kalimat Aksi',
          previewText: 'Ayo tendang bola ke dalam gawang!',
          illustrationEmoji: '⚽🥅',
          speechText: 'Ayo tendang bola masuk ke dalam gawang gol!',
          syllables: ['Ayo', 'tendang', 'bola', 'ke', 'dalam', 'gawang!'],
          themeColor: Color(0xFF10B981),
        ),
        ReadingLessonItem(
          id: 's_4',
          title: 'Ibu Memasak Sup',
          phoneticSound: 'Kalimat Kehidupan',
          previewText: 'Ibu memasak sup ayam yang lezat.',
          illustrationEmoji: '👩‍🍳🍲',
          speechText: 'Ibu memasak sup ayam hangat yang sangat lezat!',
          syllables: ['Ibu', 'memasak', 'sup', 'ayam', 'yang', 'lezat.'],
          themeColor: Color(0xFFEC4899),
        ),
        ReadingLessonItem(
          id: 's_5',
          title: 'Burung Terbang Bebas',
          phoneticSound: 'Kalimat Deskripsi Alam',
          previewText: 'Burung kecil terbang tinggi di langit biru.',
          illustrationEmoji: '🐦🌤️',
          speechText: 'Burung kecil terbang bebas tinggi di langit biru cerah!',
          syllables: ['Burung', 'kecil', 'terbang', 'tinggi', 'di', 'langit', 'biru.'],
          themeColor: Color(0xFF06B6D4),
        ),
        ReadingLessonItem(
          id: 's_6',
          title: 'Taman Bunga Ali',
          phoneticSound: 'Cerita Mini Indah',
          previewText: 'Bunga mekar wangi di kebun depan rumah.',
          illustrationEmoji: '🌸🏡',
          speechText: 'Bunga mawar merah mekar wangi di kebun depan rumah Ali!',
          syllables: ['Bunga', 'mekar', 'wangi', 'di', 'kebun', 'depan', 'rumah.'],
          themeColor: Color(0xFF8B5CF6),
        ),
        ReadingLessonItem(
          id: 's_7',
          title: 'Ali Pintar Membaca',
          phoneticSound: 'Pencapaian Hebat',
          previewText: 'Aku anak hebat yang rajin membaca buku setiap hari.',
          illustrationEmoji: '🏆📚',
          speechText: 'Aku anak hebat dan pintar yang rajin membaca buku setiap hari!',
          syllables: ['Aku', 'anak', 'hebat', 'yang', 'rajin', 'membaca', 'buku', 'setiap', 'hari.'],
          themeColor: Color(0xFFEAB308),
        ),
      ],
      testQuestions: [
        ReadingQuizQuestion(
          questionText: 'Lengkapi kalimat: "Ali suka makan ... merah manis."',
          speechAudio: 'Lengkapi kalimat: Ali suka makan titik-titik merah manis.',
          illustrationEmoji: '🍎',
          options: ['batu', 'apel', 'buku'],
          correctOptionIndex: 1,
          hintExplanation: 'Yang berwarna merah dan manis dimakan adalah apel!',
        ),
        ReadingQuizQuestion(
          questionText: 'Di manakah kucing manis tidur empuk?',
          speechAudio: 'Di manakah kucing manis tidur empuk?',
          illustrationEmoji: '🛋️',
          options: ['Di pohon', 'Di sofa', 'Di genteng'],
          correctOptionIndex: 1,
          hintExplanation: 'Kucing tidur nyenyak di atas sofa empuk!',
        ),
        ReadingQuizQuestion(
          questionText: 'Bola ditendang masuk ke mana?',
          speechAudio: 'Bola ditendang masuk ke mana?',
          illustrationEmoji: '🥅',
          options: ['Gawang', 'Kamar', 'Meja'],
          correctOptionIndex: 0,
          hintExplanation: 'Bola ditendang masuk ke dalam gawang gol!',
        ),
        ReadingQuizQuestion(
          questionText: 'Apa yang dimasak Ibu di dapur?',
          speechAudio: 'Apa yang dimasak Ibu di dapur?',
          illustrationEmoji: '🍲',
          options: ['Sup ayam lezat', 'Kertas gambar', 'Baju baru'],
          correctOptionIndex: 0,
          hintExplanation: 'Ibu memasak sup ayam yang hangat dan lezat!',
        ),
        ReadingQuizQuestion(
          questionText: 'Ke manakah burung kecil terbang tinggi?',
          speechAudio: 'Ke manakah burung kecil terbang tinggi?',
          illustrationEmoji: '🐦',
          options: ['Di dasar kolam', 'Di langit biru', 'Di dalam tanah'],
          correctOptionIndex: 1,
          hintExplanation: 'Burung terbang tinggi di langit biru cerah!',
        ),
        ReadingQuizQuestion(
          questionText: 'Apa yang mekar wangi di kebun depan rumah?',
          speechAudio: 'Apa yang mekar wangi di kebun depan rumah?',
          illustrationEmoji: '🌸',
          options: ['Batu kali', 'Bunga mawar', 'Sepatu roda'],
          correctOptionIndex: 1,
          hintExplanation: 'Bunga mawar mekar wangi di kebun!',
        ),
      ],
    ),
  ];
}
