import 'package:flutter/material.dart';

enum AnimalType {
  cat,
  chicken,
  panda,
  rabbit,
  fish,
  lion,
  tiger,
  duck,
  cow,
  monkey,
  sheep,
  owl,
  bird,
  horse,
  dog,
  koala,
  penguin,
  squirrel,
  giraffe,
  elephant,
  frog,
  dolphin,
}

class FoodItem {
  final String id;
  final String name;
  final String emoji;
  final String subtitle;
  final Color cardBg;
  final String chewSoundType; // 'crunch', 'gulp', 'nibble'

  const FoodItem({
    required this.id,
    required this.name,
    required this.emoji,
    required this.subtitle,
    required this.cardBg,
    this.chewSoundType = 'crunch',
  });
}

class AnimalProfile {
  final AnimalType type;
  final String name;
  final String title;
  final String avatarEmoji;
  final Color primaryColor;
  final Color lightBgColor;
  final String soundCall; // Onboarding voice / greeting
  final String habitatName;
  final List<String> favoriteFoodIds;
  final Map<String, String> specialReactions; // foodId -> funny voice lines

  const AnimalProfile({
    required this.type,
    required this.name,
    required this.title,
    required this.avatarEmoji,
    required this.primaryColor,
    required this.lightBgColor,
    required this.soundCall,
    required this.habitatName,
    required this.favoriteFoodIds,
    this.specialReactions = const {},
  });

  bool isFavorite(String foodId) => favoriteFoodIds.contains(foodId);
}

class FeedingGameRepository {
  // Master Food List
  static const List<FoodItem> allFoods = [
    FoodItem(
      id: 'fish',
      name: 'Ikan Segar',
      emoji: '🐟',
      subtitle: 'Gurih & bergizi',
      cardBg: Color(0xFFE0F2FE),
      chewSoundType: 'nibble',
    ),
    FoodItem(
      id: 'chicken_meat',
      name: 'Daging Ayam',
      emoji: '🍗',
      subtitle: 'Enak dan empuk',
      cardBg: Color(0xFFFEF3C7),
      chewSoundType: 'crunch',
    ),
    FoodItem(
      id: 'milk',
      name: 'Semangkok Susu',
      emoji: '🥛',
      subtitle: 'Segar dan manis',
      cardBg: Color(0xFFF1F5F9),
      chewSoundType: 'gulp',
    ),
    FoodItem(
      id: 'corn',
      name: 'Biji Jagung',
      emoji: '🌽',
      subtitle: 'Kuning dan manis',
      cardBg: Color(0xFFFEF08A),
      chewSoundType: 'nibble',
    ),
    FoodItem(
      id: 'worm',
      name: 'Cacing Tanah',
      emoji: '🪱',
      subtitle: 'Kenyal di tanah',
      cardBg: Color(0xFFFCE7F3),
      chewSoundType: 'nibble',
    ),
    FoodItem(
      id: 'grain',
      name: 'Biji Padi',
      emoji: '🌾',
      subtitle: 'Butiran renyah',
      cardBg: Color(0xFFFEF9C3),
      chewSoundType: 'nibble',
    ),
    FoodItem(
      id: 'bamboo',
      name: 'Batang Bambu',
      emoji: '🎋',
      subtitle: 'Hijau dan renyah',
      cardBg: Color(0xFFDCFCE7),
      chewSoundType: 'crunch',
    ),
    FoodItem(
      id: 'apple',
      name: 'Apel Manis',
      emoji: '🍎',
      subtitle: 'Segar berair',
      cardBg: Color(0xFFFFE4E6),
      chewSoundType: 'crunch',
    ),
    FoodItem(
      id: 'carrot',
      name: 'Wortel Renyah',
      emoji: '🥕',
      subtitle: 'Kaya vitamin A',
      cardBg: Color(0xFFFFEDD5),
      chewSoundType: 'crunch',
    ),
    FoodItem(
      id: 'lettuce',
      name: 'Daun Selada',
      emoji: '🥬',
      subtitle: 'Hijau menyehatkan',
      cardBg: Color(0xFFDCFCE7),
      chewSoundType: 'crunch',
    ),
    FoodItem(
      id: 'pellet',
      name: 'Pelet Ikan',
      emoji: '🫧',
      subtitle: 'Makanan butir koki',
      cardBg: Color(0xFFE0E7FF),
      chewSoundType: 'nibble',
    ),
    FoodItem(
      id: 'bread_crumbs',
      name: 'Remahan Roti',
      emoji: '🍞',
      subtitle: 'Empuk terapung',
      cardBg: Color(0xFFFFFBEB),
      chewSoundType: 'nibble',
    ),
    FoodItem(
      id: 'meat_steak',
      name: 'Daging Segar',
      emoji: '🥩',
      subtitle: 'Lezat penuh energi',
      cardBg: Color(0xFFFFE4E6),
      chewSoundType: 'crunch',
    ),
    FoodItem(
      id: 'fresh_grass',
      name: 'Rumput Segar',
      emoji: '🌿',
      subtitle: 'Hijau segar berembun',
      cardBg: Color(0xFFECFDF5),
      chewSoundType: 'nibble',
    ),
    FoodItem(
      id: 'banana',
      name: 'Pisang Manis',
      emoji: '🍌',
      subtitle: 'Kuning kaya energi',
      cardBg: Color(0xFFFEFCE8),
      chewSoundType: 'nibble',
    ),
    FoodItem(
      id: 'bone',
      name: 'Tulang Renyah',
      emoji: '🦴',
      subtitle: 'Gurih digigit',
      cardBg: Color(0xFFF1F5F9),
      chewSoundType: 'crunch',
    ),
    FoodItem(
      id: 'insect',
      name: 'Jangkrik Kecil',
      emoji: '🦗',
      subtitle: 'Kerenyahan serangga',
      cardBg: Color(0xFFFEF3C7),
      chewSoundType: 'crunch',
    ),
    FoodItem(
      id: 'eucalyptus',
      name: 'Daun Segar',
      emoji: '🍃',
      subtitle: 'Harum menyegarkan',
      cardBg: Color(0xFFF0FDF4),
      chewSoundType: 'nibble',
    ),
    FoodItem(
      id: 'acorn',
      name: 'Kacang Kenari',
      emoji: '🌰',
      subtitle: 'Gurih berlemak',
      cardBg: Color(0xFFFEF3C7),
      chewSoundType: 'crunch',
    ),
    FoodItem(
      id: 'honey',
      name: 'Madu Manis',
      emoji: '🍯',
      subtitle: 'Manis keemasan',
      cardBg: Color(0xFFFEF9C3),
      chewSoundType: 'gulp',
    ),
    // Challengers (funny wrong foods)
    FoodItem(
      id: 'chili',
      name: 'Cabai Merah',
      emoji: '🌶️',
      subtitle: 'Hati-hati pedas!',
      cardBg: Color(0xFFFEE2E2),
      chewSoundType: 'crunch',
    ),
  ];

  static const List<AnimalProfile> animals = [
    AnimalProfile(
      type: AnimalType.cat,
      name: 'Si Meong',
      title: 'Kucing Abu & Putih',
      avatarEmoji: '🐱',
      primaryColor: Color(0xFF64748B),
      lightBgColor: Color(0xFFF8FAFC),
      soundCall: 'Meoww! Meong lapar nih, mau makan yang gurih-gurih!',
      habitatName: 'Karpet Rumah Lembut',
      favoriteFoodIds: ['fish', 'chicken_meat', 'milk'],
      specialReactions: {
        'carrot': 'Hee? Meong kan bukan kelinci! Meong mau ikan renyah!',
        'corn': 'Kok dikasih jagung? Meong ga bisa makan biji-bijian!',
        'chili': 'Haaah haaah! Pedaaaasss! Kuping Meong berasap, tolong susu dingin meoong!',
        'bamboo': 'Aduh keras banget, gigi Meong copot nanti!',
      },
    ),
    AnimalProfile(
      type: AnimalType.chicken,
      name: 'Si Jago',
      title: 'Ayam Jantan',
      avatarEmoji: '🐔',
      primaryColor: Color(0xFFEF4444),
      lightBgColor: Color(0xFFFEF2F2),
      soundCall: 'Kukuruyuuuk! Ada biji-biji lezat buat Si Jago?',
      habitatName: 'Halaman Berumput',
      favoriteFoodIds: ['corn', 'grain', 'worm'],
      specialReactions: {
        'fish': 'Wah ikannya terlalu besar, paruh Si Jago ga muat!',
        'milk': 'Kocok-kocok airnya kecipratan! Ayam sukanya makan biji!',
        'chili': 'Petok petok petook! Haaah pedaas berasap paruh Si Jago terbakar!',
        'bamboo': 'Ini mah kayu bukan makanan ayam!',
      },
    ),
    AnimalProfile(
      type: AnimalType.panda,
      name: 'Si Gembul',
      title: 'Panda Lucu',
      avatarEmoji: '🐼',
      primaryColor: Color(0xFF10B981),
      lightBgColor: Color(0xFFF0FDF4),
      soundCall: 'Gembul mau bambu hijau segar yang kres-kres!',
      habitatName: 'Hutan Bambu Rindang',
      favoriteFoodIds: ['bamboo', 'apple', 'carrot'],
      specialReactions: {
        'fish': 'Uweeek! Bau amis, Panda kan sukanya bambu manis!',
        'worm': 'Ih ada cacing geli! Jauhin dari Panda!',
        'chili': 'Haaaah pedass panas! Pipi Panda merah berasap! Haaatsyii!',
        'pellet': 'Kecil banget, ga bikin perut gembul kenyang!',
      },
    ),
    AnimalProfile(
      type: AnimalType.rabbit,
      name: 'Si Fluffy',
      title: 'Kelinci Putih',
      avatarEmoji: '🐰',
      primaryColor: Color(0xFFEC4899),
      lightBgColor: Color(0xFFFDF2F8),
      soundCall: 'Kelinci suka sayuran renyah yang kriuk-kriuk!',
      habitatName: 'Kebun Wortel Ceria',
      favoriteFoodIds: ['carrot', 'lettuce', 'apple'],
      specialReactions: {
        'fish': 'Telinga Kelinci langsung turun, ini bukan sayur!',
        'chicken_meat': 'Kelinci cuma makan tanaman segar ya teman!',
        'worm': 'Ih geli! Kelinci maunya wortel oranye!',
        'chili': 'Waaaah pedaasss! Telinga Kelinci keluar asap kebakaran!',
      },
    ),
    AnimalProfile(
      type: AnimalType.lion,
      name: 'Si Simba',
      title: 'Singa Pemberani',
      avatarEmoji: '🦁',
      primaryColor: Color(0xFFD97706),
      lightBgColor: Color(0xFFFFFBEB),
      soundCall: 'Auuuum! Simba raja hutan lapar, mau daging segar!',
      habitatName: 'Padang Rumput Savana',
      favoriteFoodIds: ['meat_steak', 'chicken_meat', 'bone'],
      specialReactions: {
        'fresh_grass': 'Singa raja sabana makan daging, bukan rumput!',
        'carrot': 'Wortel buat kelinci, Simba maunya daging lezat!',
        'chili': 'Haaaah! Auuuum! Surai Simba berdiri kepedasan panas!',
      },
    ),
    AnimalProfile(
      type: AnimalType.tiger,
      name: 'Si Belang',
      title: 'Harimau Belang',
      avatarEmoji: '🐯',
      primaryColor: Color(0xFFEA580C),
      lightBgColor: Color(0xFFFFF7ED),
      soundCall: 'Ggrrrr! Belang harimau tangguh mau makan daging enak!',
      habitatName: 'Hutan Belantara Lebat',
      favoriteFoodIds: ['meat_steak', 'fish', 'chicken_meat'],
      specialReactions: {
        'bamboo': 'Ini bambu makanan panda, Belang sukanya daging!',
        'banana': 'Pisang manis buat monyet, mana daging Belang?',
        'chili': 'Ggrrr haaah! Lidah belang kebakar cabai pedas!',
      },
    ),
    AnimalProfile(
      type: AnimalType.duck,
      name: 'Si Kwek',
      title: 'Bebek Kuning Ceria',
      avatarEmoji: '🦆',
      primaryColor: Color(0xFFCA8A04),
      lightBgColor: Color(0xFFFEFCE8),
      soundCall: 'Kwek kwek kwek! Ada cacing atau biji padi di danau?',
      habitatName: 'Kolam Teratai Sejuk',
      favoriteFoodIds: ['worm', 'grain', 'corn'],
      specialReactions: {
        'meat_steak': 'Dagingnya kegedean buat paruh Si Kwek!',
        'chili': 'Kwek kwek petok! Tenggorokan bebek kepanasan!',
      },
    ),
    AnimalProfile(
      type: AnimalType.cow,
      name: 'Si Mumu',
      title: 'Sapi Perah Manis',
      avatarEmoji: '🐮',
      primaryColor: Color(0xFF475569),
      lightBgColor: Color(0xFFF8FAFC),
      soundCall: 'Mooo! Mumu mau kunyah rumput segar dan jagung manis!',
      habitatName: 'Padang Rumput Hijau',
      favoriteFoodIds: ['fresh_grass', 'corn', 'apple'],
      specialReactions: {
        'meat_steak': 'Moo! Sapi vegetarian hanya makan tanaman hijau!',
        'chili': 'Moooo haaah! Hidung Mumu keluar uap pedas!',
      },
    ),
    AnimalProfile(
      type: AnimalType.monkey,
      name: 'Si Miko',
      title: 'Monyet Lincah',
      avatarEmoji: '🐵',
      primaryColor: Color(0xFF92400E),
      lightBgColor: Color(0xFFFEF3C7),
      soundCall: 'Uu-aa-aa! Miko suka buah manis dan pisang emas!',
      habitatName: 'Pohon Buah Rindang',
      favoriteFoodIds: ['banana', 'apple', 'acorn'],
      specialReactions: {
        'fish': 'Uweeek! Monyet sukanya buah pisang manis!',
        'chili': 'Uu-aa-aa! Ekor Miko melintir kepedasan!',
      },
    ),
    AnimalProfile(
      type: AnimalType.sheep,
      name: 'Si Mbek',
      title: 'Domba Bulu Lembut',
      avatarEmoji: '🐑',
      primaryColor: Color(0xFF0D9488),
      lightBgColor: Color(0xFFF0FDFA),
      soundCall: 'Mbeeek! Ada rumput hijau segar buat domba putih?',
      habitatName: 'Bukit Padang Rumput',
      favoriteFoodIds: ['fresh_grass', 'lettuce', 'grain'],
      specialReactions: {
        'meat_steak': 'Mbeeek! Domba cuma makan rumput dan dedaunan!',
        'chili': 'Mbeeek panas! Bulu domba yang putih jadi merah!',
      },
    ),
    AnimalProfile(
      type: AnimalType.owl,
      name: 'Si Hoot',
      title: 'Burung Hantu Bijak',
      avatarEmoji: '🦉',
      primaryColor: Color(0xFF78350F),
      lightBgColor: Color(0xFFFEF3C7),
      soundCall: 'Hoot hoot! Mata bulat Si Hoot mencari mangsa serangga!',
      habitatName: 'Dahan Pohon Malam Hari',
      favoriteFoodIds: ['insect', 'worm', 'meat_steak'],
      specialReactions: {
        'banana': 'Burung hantu karnivora ga makan buah!',
        'chili': 'Hoot hoot haaah! Mata Si Hoot muter kepedasan!',
      },
    ),
    AnimalProfile(
      type: AnimalType.bird,
      name: 'Si Pipit',
      title: 'Burung Berkicau Merdu',
      avatarEmoji: '🐦',
      primaryColor: Color(0xFF0284C7),
      lightBgColor: Color(0xFFF0F9FF),
      soundCall: 'Cit cit cuit! Burung kecil mau butiran biji padi!',
      habitatName: 'Sarang Ranting Pohon',
      favoriteFoodIds: ['grain', 'corn', 'worm'],
      specialReactions: {
        'meat_steak': 'Terlalu berat, paruh Si Pipit ga kuat!',
        'chili': 'Cit cit cuit panas terbakar paruh mungil!',
      },
    ),
    AnimalProfile(
      type: AnimalType.horse,
      name: 'Si Ksatria',
      title: 'Kuda Poni Tangguh',
      avatarEmoji: '🐴',
      primaryColor: Color(0xFFB45309),
      lightBgColor: Color(0xFFFFFBEB),
      soundCall: 'Hii-hee-hee! Kuda gagah mau makan wortel dan rumput!',
      habitatName: 'Padang Pacuan Luas',
      favoriteFoodIds: ['fresh_grass', 'apple', 'carrot'],
      specialReactions: {
        'fish': 'Kuda gagah makannya tumbuhan bernutrisi!',
        'chili': 'Hii-hee! Kuda lari kencang nyari air minum!',
      },
    ),
    AnimalProfile(
      type: AnimalType.dog,
      name: 'Si Milo',
      title: 'Anjing Sahabat Setia',
      avatarEmoji: '🐶',
      primaryColor: Color(0xFF9A3412),
      lightBgColor: Color(0xFFFFF7ED),
      soundCall: 'Guk guk! Milo senang bermain dan gigit tulang renyah!',
      habitatName: 'Pekarangan Rumah Asri',
      favoriteFoodIds: ['bone', 'meat_steak', 'chicken_meat'],
      specialReactions: {
        'fresh_grass': 'Guk guk? Milo bukan sapi perah pemakan rumput!',
        'chili': 'Guk guk haaah! Lidah Milo menjulur panjang kepedasan!',
      },
    ),
    AnimalProfile(
      type: AnimalType.koala,
      name: 'Si Koko',
      title: 'Koala Pemanjat',
      avatarEmoji: '🐨',
      primaryColor: Color(0xFF64748B),
      lightBgColor: Color(0xFFF8FAFC),
      soundCall: 'Nguuuk! Koala imut mau daun segar yang wangi!',
      habitatName: 'Pohon Hutan Tenang',
      favoriteFoodIds: ['eucalyptus', 'apple', 'lettuce'],
      specialReactions: {
        'fish': 'Bau amis! Koala cuma suka daun segar di pohon!',
        'chili': 'Haaah! Koala langsung terbangun dari tidur kepedasan!',
      },
    ),
    AnimalProfile(
      type: AnimalType.penguin,
      name: 'Si Piko',
      title: 'Pinguin Lucu Kutub',
      avatarEmoji: '🐧',
      primaryColor: Color(0xFF0F172A),
      lightBgColor: Color(0xFFF1F5F9),
      soundCall: 'Waddle waddle! Dingin di es, Piko mau ikan segar!',
      habitatName: 'Gunung Es Kutub Selatan',
      favoriteFoodIds: ['fish', 'pellet', 'bread_crumbs'],
      specialReactions: {
        'fresh_grass': 'Di kutub es ga ada rumput, Piko mau ikan!',
        'chili': 'Waaah es di badan Piko langsung mencair kepedasan!',
      },
    ),
    AnimalProfile(
      type: AnimalType.squirrel,
      name: 'Si Ciki',
      title: 'Tupai Ekor Lebat',
      avatarEmoji: '🐿️',
      primaryColor: Color(0xFFC2410C),
      lightBgColor: Color(0xFFFFF7ED),
      soundCall: 'Cik-cik! Tupai lincah mau kumpulkan kacang kenari!',
      habitatName: 'Lubang Batang Pohon',
      favoriteFoodIds: ['acorn', 'corn', 'apple'],
      specialReactions: {
        'meat_steak': 'Cik-cik! Gigi tupai cuma buat gigit biji kacang!',
        'chili': 'Ciiik! Ekor lebat tupai bergoyang kencang kepedasan!',
      },
    ),
    AnimalProfile(
      type: AnimalType.giraffe,
      name: 'Si Jerapah',
      title: 'Jerapah Leher Tinggi',
      avatarEmoji: '🦒',
      primaryColor: Color(0xFFD97706),
      lightBgColor: Color(0xFFFEF3C7),
      soundCall: 'Halo sahabat! Leher jerapah panjang petik daun segar!',
      habitatName: 'Pohon Akasia Sabana',
      favoriteFoodIds: ['eucalyptus', 'fresh_grass', 'apple'],
      specialReactions: {
        'meat_steak': 'Jerapah berleher panjang pecinta dedaunan!',
        'chili': 'Aduh leher jerapah yang panjang terasa terbakar pedas!',
      },
    ),
    AnimalProfile(
      type: AnimalType.elephant,
      name: 'Si Gani',
      title: 'Gajah Belalai Pintar',
      avatarEmoji: '🐘',
      primaryColor: Color(0xFF475569),
      lightBgColor: Color(0xFFF1F5F9),
      soundCall: 'Teroooet! Belalai gajah semprot air mau pisang banyak!',
      habitatName: 'Hutan Rimba Tropis',
      favoriteFoodIds: ['banana', 'bamboo', 'apple'],
      specialReactions: {
        'fish': 'Gajah ga makan ikan, gajah mau buah segar!',
        'chili': 'Terooet bersin kencang! Belalai gajah kena cabai pedas!',
      },
    ),
    AnimalProfile(
      type: AnimalType.frog,
      name: 'Si Kodok',
      title: 'Katak Hijau Melompat',
      avatarEmoji: '🐸',
      primaryColor: Color(0xFF16A34A),
      lightBgColor: Color(0xFFF0FDF4),
      soundCall: 'Kroek kroek! Lidah kodok cepat tangkap serangga!',
      habitatName: 'Daun Teratai Kolam',
      favoriteFoodIds: ['insect', 'worm', 'pellet'],
      specialReactions: {
        'fresh_grass': 'Kodok bukan pemakan rumput, kroek kroek!',
        'chili': 'Kroek kroek! Perut kodok melembung kepanasan pedas!',
      },
    ),
    AnimalProfile(
      type: AnimalType.dolphin,
      name: 'Si Lumba',
      title: 'Lumba-lumba Cerdas',
      avatarEmoji: '🐬',
      primaryColor: Color(0xFF0284C7),
      lightBgColor: Color(0xFFF0F9FF),
      soundCall: 'Klik klik klik! Lumba-lumba melompat gembira mau ikan!',
      habitatName: 'Samudra Biru Jernih',
      favoriteFoodIds: ['fish', 'pellet', 'bread_crumbs'],
      specialReactions: {
        'fresh_grass': 'Di dalam laut ga ada rumput padang, mau ikan!',
        'chili': 'Byuuur! Lumba langsung menyelam ke dasar laut minum air!',
      },
    ),
  ];

  static FoodItem getFoodById(String id) {
    return allFoods.firstWhere(
      (f) => f.id == id,
      orElse: () => allFoods.first,
    );
  }
}
